import test from 'node:test';
import assert from 'node:assert/strict';
import { createApi } from '../src/server.mjs';

test('API protects dashboard, uses Firebase session cookies, checks profiles, and clears logout', async () => {
  const row = { id: 'firebase-uid', full_name: 'Test Admin', email: 'admin@example.test', role: 'ADMIN', is_active: true };
  const signedIn = [];
  const revoked = new Set();
  const sessions = { signIn: async (email, password) => { signedIn.push({ email, password }); return password === 'test-password-with-length' ? { uid: row.id, cookie: 'signed-cookie', seconds: 28800 } : null; }, verify: async token => token === 'signed-cookie' && !revoked.has(token) ? { uid: row.id } : null, revoke: token => revoked.add(token) };
  const services = { health: async () => { }, getUser: async id => id === row.id ? row : null, touchLogin: async () => { }, dashboard: async () => ({ stats: { active: 0 } }), inventoryList: async () => ({ items: [], categories: [] }), workspace: async role => ({ role, customers: [] }), createCustomer: async (actor, input) => ({ id: 'customer-1', actor, ...input }), saveSettings: async (actor, input) => input };
  const server = createApi({ services, sessions });
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  const base = `http://127.0.0.1:${server.address().port}`;
  try {
    assert.equal((await fetch(base + '/api/dashboard')).status, 401);
    assert.equal((await fetch(base + '/api/rental-events')).status, 204);
    assert.equal((await fetch(base + '/api/inventory')).status, 401);
    assert.equal((await fetch(base + '/api/inventory', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: '{}' })).status, 401);
    const login = async (password, headers = {}) => fetch(base + '/api/auth/login', { method: 'POST', headers: { 'Content-Type': 'application/json', ...headers }, body: JSON.stringify({ email: row.email, password }) });
    assert.equal((await login('incorrect')).status, 401);
    assert.equal((await login('test-password-with-length', { Origin: 'https://untrusted.example' })).status, 403);
    const response = await login('test-password-with-length');
    assert.equal(response.status, 200);
    const setCookie = response.headers.get('set-cookie');
    assert.match(setCookie, /HttpOnly/); assert.match(setCookie, /SameSite=Strict/);
    const cookie = setCookie.split(';')[0];
    assert.equal((await fetch(base + '/api/inventory/1', { method: 'PATCH', headers: { Cookie: cookie, Origin: 'https://untrusted.example', 'Content-Type': 'application/json' }, body: '{}' })).status, 403);
    assert.equal((await response.json()).user.password_hash, undefined);
    const dashboard = await fetch(base + '/api/dashboard', { headers: { Cookie: cookie } });
    assert.equal(dashboard.status, 200);
    const eventStream = await fetch(base + '/api/rental-events', { headers: { Cookie: cookie } });
    assert.equal(eventStream.status, 200);
    assert.match(eventStream.headers.get('content-type'), /text\/event-stream/);
    const eventReader = eventStream.body.getReader();
    const readyFrame = await eventReader.read();
    assert.match(new TextDecoder().decode(readyFrame.value), /event: ready/);
    await eventReader.cancel();
    const workspace = await fetch(base + '/api/workspace', { headers: { Cookie: cookie } }); assert.equal(workspace.status, 200); assert.equal((await workspace.json()).role, 'OPERATOR');
    const customer = await fetch(base + '/api/customers', { method: 'POST', headers: { Cookie: cookie, 'Content-Type': 'application/json' }, body: JSON.stringify({ fullName: 'Customer' }) }); assert.equal(customer.status, 201);
    row.role = 'user';
    assert.equal((await fetch(base + '/api/dashboard', { headers: { Cookie: cookie } })).status, 401);
    assert.equal((await login('test-password-with-length')).status, 403);
    row.role = 'OWNER';
    const ownerLogin = await login('test-password-with-length');
    assert.equal(ownerLogin.status, 200);
    assert.equal((await ownerLogin.json()).user.role, 'OWNER');
    row.role = 'admin';
    const lowercaseLogin = await login('test-password-with-length');
    assert.equal(lowercaseLogin.status, 200);
    assert.equal((await lowercaseLogin.json()).user.role, 'OPERATOR');
    row.role = 'admin';
    const lowercaseWorkspace = await fetch(base + '/api/workspace', { headers: { Cookie: cookie } });
    assert.equal(lowercaseWorkspace.status, 200);
    assert.equal((await lowercaseWorkspace.json()).role, 'OPERATOR');
    row.is_active = 0;
    assert.equal((await fetch(base + '/api/dashboard', { headers: { Cookie: cookie } })).status, 401);
    row.is_active = 1;
    const next = await login('test-password-with-length');
    const nextCookie = next.headers.get('set-cookie').split(';')[0];
    assert.equal((await fetch(base + '/api/auth/logout', { method: 'POST', headers: { Cookie: nextCookie } })).status, 200);
    assert.equal((await fetch(base + '/api/auth/me', { headers: { Cookie: nextCookie } })).status, 401);
    assert.ok(signedIn.some(entry => entry.email === row.email));
  } finally { await new Promise(resolve => server.close(resolve)); }
});
