export const settingsTabs=owner=>[
  {id:'business',label:'Business',icon:'box'},
  {id:'appearance',label:'Appearance',icon:'sun'},
  {id:'preferences',label:'Preferences',icon:'settings'},
  ...(owner?[{id:'users',label:'Users',icon:'users'}]:[]),
  {id:'account',label:'Account & security',icon:'out'}
];

export function renderSettings({model,user,appearance,tab,draft,dirty,saving,preferences,users},h) {
  const {escape:e,icon}=h,owner=user.role==='OWNER',s=model.settings||{},tabs=settingsTabs(owner);
  const active=tabs.some(row=>row.id===tab)?tab:'business';
  const values=draft||{businessName:s.business_name||'Rent & Play',location:s.location||'Los Baños, Laguna',currency:s.currency||'PHP',timezone:s.timezone||'Asia/Manila',defaultLateGraceHours:s.default_late_grace_hours??0};
  const title=(eyebrow,name,note)=>`<div class="settings-section-title"><span class="eyebrow">${eyebrow}</span><h3>${name}</h3><p>${note}</p></div>`;
  const options=(rows,selected)=>rows.map(([value,label])=>`<option value="${value}" ${value===selected?'selected':''}>${label}</option>`).join('');
  let content='';
  if(active==='business')content=`<section class="panel settings-card">${title('BUSINESS PROFILE','Your rental workspace',owner?'Business details are shared with everyone in this workspace.':'Workspace details are managed by the owner.')}
    ${owner?`<form id="business-form" class="admin-form"><fieldset ${saving?'disabled':''}><div class="form-grid"><label>Business name<input name="businessName" value="${e(values.businessName)}" maxlength="150" required/></label><label>Location<input name="location" value="${e(values.location)}" maxlength="255" required/></label><label>Currency<input name="currency" value="${e(values.currency)}" readonly/><small>Reports currently display Philippine pesos (PHP).</small></label><label>Timezone<input name="timezone" value="${e(values.timezone)}" readonly/><small>Reports use Philippine time (Asia/Manila).</small></label></div><label>Default late grace period (hours)<input name="defaultLateGraceHours" type="number" min="0" max="168" step="0.5" value="${e(values.defaultLateGraceHours)}" required/><small>Administrative default only. This does not change recorded due dates, penalties, or the analytics overdue calculation.</small></label><p class="settings-draft-note" role="status">${saving?'Saving changes…':dirty?'You have unsaved changes. Your draft is kept while switching tabs.':'Changes apply after you select Save business settings.'}</p><p class="form-error" role="alert"></p><div class="settings-form-footer"><button class="secondary" id="business-discard" type="button" ${dirty?'':'disabled'}>Discard changes</button><button class="primary" type="submit">${saving?'Saving…':'Save business settings'}</button></div></fieldset></form>`:`<dl class="settings-account-details"><div><dt>Business name</dt><dd>${e(values.businessName)}</dd></div><div><dt>Location</dt><dd>${e(values.location)}</dd></div><div><dt>Currency</dt><dd>${e(values.currency)}</dd></div><div><dt>Timezone</dt><dd>${e(values.timezone)}</dd></div></dl><div class="info-box">Only owners can edit business settings.</div>`}</section>`;
  if(active==='appearance')content=`<section class="panel settings-card">${appearance}<div class="settings-tip"><strong>Personal to this browser</strong><p>Your appearance choice is remembered on this device. It does not change another staff member’s screen.</p></div></section>`;
  if(active==='preferences')content=`<section class="panel settings-card">${title('YOUR WORKFLOW','Workspace preferences','Saved on this browser. These options do not change business data or other devices.')}<form id="preferences-form" class="admin-form"><label class="settings-checkbox-row"><input name="autoRefresh" type="checkbox" ${preferences.autoRefresh?'checked':''}/><span>Automatically refresh workspace data<small>Check for updates every 30 seconds while the page is visible. Paused in Settings and while editing. Manual Refresh is always available.</small></span></label><div class="settings-divider"></div><h4>Default analytics view</h4><p>Use these defaults when opening Reports in a new session. You can still adjust filters inside Reports.</p><div class="form-grid"><label>Default period<select name="reportPeriod">${options([['7d','Last 7 days'],['30d','Last 30 days'],['90d','Last 90 days'],['365d','Last 365 days']],preferences.reportPeriod)}</select></label><label>Default trend grouping<select name="reportGrouping">${options([['auto','Automatic'],['daily','Daily'],['weekly','Weekly'],['monthly','Monthly']],preferences.reportGrouping)}</select></label></div><p class="form-error" role="alert"></p><div class="settings-form-footer"><button type="button" id="preferences-reset" class="secondary">Restore defaults</button><button type="submit" class="primary">Save preferences</button></div></form></section>`;
  if(active==='users')content=`${users()}<div class="settings-tip"><strong>Choose access carefully</strong><p>Owners can manage business settings and users. Operators handle daily rental operations. Deactivate an account to remove its workspace access. You cannot deactivate your own account here.</p></div>`;
  if(active==='account')content=`<section class="panel settings-card">${title('ACCOUNT & SECURITY','Your account','Review your signed-in account and keep your access secure.')}<dl class="settings-account-details"><div><dt>Name</dt><dd>${e(user.name)}</dd></div><div><dt>Email</dt><dd>${e(user.email)}</dd></div><div><dt>Workspace role</dt><dd>${e(user.role)}</dd></div><div><dt>Sign-in provider</dt><dd>Firebase Authentication</dd></div></dl><div class="settings-action-row"><div><h4>Profile details</h4><p>Update your name and personal profile information.</p></div><button class="secondary" data-page="Profile">View profile</button></div><div class="settings-action-row"><div><h4>Password reset</h4><p>Send a reset link to <strong>${e(user.email)}</strong>. Complete the password change in your email.</p></div><button class="secondary" id="settings-password-reset">Send reset email</button></div><p class="settings-security-status" role="status"></p><div class="settings-tip"><strong>On a shared computer?</strong><p>Sign out from the account menu when you finish. Your password is never shown on this page.</p></div></section>`;
  return `<div class="module-heading settings-heading"><div><span class="eyebrow">WORKSPACE PREFERENCES</span><h2>A workspace that works for you</h2><p>One place for your business, personal preferences, and account.</p></div><span class="settings-role">${owner?'Owner workspace':'Operator workspace'}</span></div><div class="settings-tabs" role="tablist" aria-label="Settings sections" aria-orientation="horizontal">${tabs.map(row=>`<button type="button" role="tab" id="settings-tab-${row.id}" data-settings-tab="${row.id}" aria-controls="settings-panel-${row.id}" aria-selected="${row.id===active}" tabindex="${row.id===active?0:-1}">${icon(row.icon)}<span>${row.label}</span></button>`).join('')}</div><div class="settings-tab-panel" role="tabpanel" id="settings-panel-${active}" aria-labelledby="settings-tab-${active}" tabindex="0">${content}</div>`;
}
