export function createWorkspaceUI(h) {
  const {api,escape:e,showModal,modal,toast,money,formatDate,icon}=h;
  let model=null,loading=null,search='',redraw=()=>{};
  const activeRates=()=>model.rates.filter(rate=>rate.is_active!==false);
  const status=value=>`<span class="badge ${e(String(value||'unknown').toLowerCase().replaceAll('_','-'))}">${e(String(value||'Unknown').replaceAll('_',' '))}</span>`;
  const load=async(force=false)=>{if(model&&!force)return model;if(!loading||force)loading=api('/workspace').then(value=>(model=value));return loading;};
  const refresh=async()=>load(true);
  const empty=(title,text)=>`<div class="workspace-empty">${icon('box')}<h3>${e(title)}</h3><p>${e(text)}</p></div>`;
  const table=(heads,rows)=>`<div class="admin-table-scroll"><table class="admin-table"><thead><tr>${heads.map(v=>`<th>${v}</th>`).join('')}</tr></thead><tbody>${rows}</tbody></table></div>`;
  const pageHeader=(eyebrow,title,text,action='')=>`<div class="module-heading"><div><span class="eyebrow">${eyebrow}</span><h2>${title}</h2><p>${text}</p></div>${action}</div>`;
  const includes=(row,keys)=>keys.some(key=>String(row[key]||'').toLowerCase().includes(search.toLowerCase()));

  function customers() {
    const rows=model.customers.filter(c=>includes(c,['full_name','customer_code','email','phone']));
    return `${pageHeader('CUSTOMER DIRECTORY','Customers','Manage customer contact details and account status.','<button class="primary" id="customer-add">+ Add customer</button>')}<section class="panel admin-module"><div class="module-toolbar"><label class="module-search">${icon('search')}<input id="module-search" value="${e(search)}" placeholder="Search customers" aria-label="Search customers"/></label><span>${rows.length} customer(s)</span></div>${rows.length?table(['CUSTOMER','CONTACT','ADDRESS','STATUS',''],rows.map(c=>`<tr><td><strong>${e(c.full_name)}</strong><small>${e(c.customer_code)}</small></td><td>${e(c.email||'No email')}<small>${e(c.phone||'No phone')}</small></td><td>${e(c.address||'Not provided')}</td><td>${status(c.is_active===false?'Inactive':'Active')}</td><td><div class="row-actions"><button class="text-button" data-customer-edit="${e(c.id)}">Edit</button><button class="text-button" data-customer-action="${e(c.id)}">${c.is_active===false?'Restore':'Archive'}</button></div></td></tr>`).join('')):empty('No customers found','Add a customer or adjust your search.')}</section>`;
  }

  function customerForm(customer={}) {
    showModal(customer.id?'Edit customer':'Add customer',`<form id="customer-form" class="admin-form"><div class="form-grid"><label>Full name<input name="fullName" value="${e(customer.full_name||'')}" maxlength="150" required/></label><label>Customer code<input name="code" value="${e(customer.customer_code||'')}" pattern="[A-Za-z0-9][A-Za-z0-9_-]+" maxlength="50" placeholder="CUST-001" required/></label><label>Email<input type="email" name="email" value="${e(customer.email||'')}" maxlength="191"/></label><label>Phone<input name="phone" value="${e(customer.phone||'')}" maxlength="40"/></label></div><label>Address<textarea name="address" maxlength="500" rows="3">${e(customer.address||'')}</textarea></label><p class="form-error" role="alert"></p><div class="form-actions"><button type="button" class="secondary" data-close>Cancel</button><button class="primary" type="submit">Save customer</button></div></form>`);
    modal.querySelector('[data-close]').onclick=()=>modal.close();
    modal.querySelector('form').onsubmit=async event=>{event.preventDefault();const form=event.currentTarget,button=form.querySelector('[type="submit"]'),error=form.querySelector('.form-error');button.disabled=true;try{await api(customer.id?`/customers/${customer.id}`:'/customers',{method:customer.id?'PATCH':'POST',body:JSON.stringify(Object.fromEntries(new FormData(form)))});await refresh();modal.close();toast(customer.id?'Customer updated.':'Customer added.');redraw();}catch(problem){error.textContent=problem.message;button.disabled=false;}};
  }

  function transactions(mode) {
    let rows=[...model.transactions];
    if(mode==='Returns')rows=rows.filter(r=>r.confirmed_return_at||/RETURN|COMPLETED/i.test(`${r.status} ${r.transaction_type||''}`));
    if(mode==='Rentals')rows=rows.filter(r=>['ACTIVE','PENDING_VERIFICATION'].includes(r.status));
    rows=rows.filter(r=>includes(r,['rental_code','item_name','customer_name','status']));
    const title=mode==='Transaction History'?'Transaction History':mode;
    return `${pageHeader('TRANSACTION MONITORING',title,mode==='Returns'?'Track return confirmations and completed handoffs.':mode==='Rentals'?'Monitor open and pending rentals.':'Review every rental and return record.')}<section class="panel admin-module"><div class="module-toolbar"><label class="module-search">${icon('search')}<input id="module-search" value="${e(search)}" placeholder="Search transactions" aria-label="Search transactions"/></label><span>${rows.length} record(s)</span></div>${rows.length?table(['TRANSACTION','CUSTOMER','RENTAL DATE','DUE / RETURNED','STATUS','FEES'],rows.map(r=>`<tr><td><strong>${e(r.item_name)}</strong><small>${e(r.rental_code||r.id)} · ${e(r.item_code)}</small></td><td>${e(r.customer_name)}</td><td>${e(formatDate(r.confirmed_rental_at||r.created_at))}</td><td>${e(formatDate(r.confirmed_return_at||r.due_at))}</td><td>${status(r.status)}</td><td><strong>${money(r.rental_fee)}</strong><small>Deposit ${money(r.deposit_amount)}</small></td></tr>`).join('')):empty('No matching transactions','Records will appear after the mobile and terminal workflow creates them.')}</section>`;
  }

  function rates() {
    const current=activeRates().filter(r=>includes(r,['item_name','item_code','rate_type']));
    return `${pageHeader('PRICING CONTROL','Rates & Fees','Update active rental pricing without changing historical transactions.','<button class="primary" id="rate-add">Update a rate</button>')}<div class="module-stats"><article><span>Active rates</span><strong>${current.length}</strong></article><article><span>Average rental rate</span><strong>${money(current.length?current.reduce((s,r)=>s+Number(r.rental_rate||0),0)/current.length:0)}</strong></article><article><span>Average deposit</span><strong>${money(current.length?current.reduce((s,r)=>s+Number(r.deposit_amount||0),0)/current.length:0)}</strong></article></div><section class="panel admin-module"><div class="module-toolbar"><label class="module-search">${icon('search')}<input id="module-search" value="${e(search)}" placeholder="Search equipment rates"/></label><span>Historical rates are retained</span></div>${current.length?table(['EQUIPMENT','BASIS','RENTAL RATE','DEPOSIT','LATE PENALTY','EFFECTIVE'],current.map(r=>`<tr><td><strong>${e(r.item_name)}</strong><small>${e(r.item_code)}</small></td><td>${e(r.rate_type)}</td><td><strong>${money(r.rental_rate)}</strong></td><td>${money(r.deposit_amount)}</td><td>${money(r.late_penalty_rate)}</td><td>${e(formatDate(r.effective_from))}</td></tr>`).join('')):empty('No active rates','Add equipment and configure its rental pricing.')}</section>`;
  }

  function rateForm() {
    const items=model.items.filter(i=>i.is_active!==false).sort((a,b)=>a.name.localeCompare(b.name));
    showModal('Update equipment rate',`<form id="rate-form" class="admin-form"><label>Equipment<select name="itemId" required><option value="">Select equipment</option>${items.map(i=>`<option value="${e(i.id)}">${e(i.name)} · ${e(i.item_code)}</option>`).join('')}</select></label><div class="form-grid"><label>Rate basis<select name="rateType"><option>DAILY</option><option>HOURLY</option><option>FLAT</option></select></label><label>Rental rate<input name="rentalRate" type="number" min="0" step="0.01" required/></label><label>Refundable deposit<input name="deposit" type="number" min="0" step="0.01" value="0"/></label><label>Late penalty<input name="latePenalty" type="number" min="0" step="0.01" value="0"/></label></div><div class="info-box">The previous active rate will be closed and kept in pricing history.</div><p class="form-error"></p><div class="form-actions"><button type="button" class="secondary" data-close>Cancel</button><button class="primary" type="submit">Save new rate</button></div></form>`);
    modal.querySelector('[data-close]').onclick=()=>modal.close();modal.querySelector('form').onsubmit=async event=>{event.preventDefault();const form=event.currentTarget;try{await api('/rates',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(form)))});await refresh();modal.close();toast('Rate updated.');redraw();}catch(problem){form.querySelector('.form-error').textContent=problem.message;}};
  }

  function maintenance() {
    const open=model.maintenance.filter(r=>r.status==='IN_PROGRESS'),done=model.maintenance.filter(r=>r.status==='COMPLETED');
    return `${pageHeader('EQUIPMENT CARE','Maintenance','Track inspections, repairs, and completed maintenance work.','<button class="secondary" data-page="Inventory">Open equipment</button>')}<div class="module-stats"><article><span>In progress</span><strong>${open.length}</strong></article><article><span>Completed</span><strong>${done.length}</strong></article><article><span>Total records</span><strong>${model.maintenance.length}</strong></article></div><section class="panel admin-module">${model.maintenance.length?table(['EQUIPMENT','REASON','STARTED','COMPLETED','STATUS'],model.maintenance.map(r=>`<tr><td><strong>${e(r.item_name)}</strong><small>${e(r.item_code)}</small></td><td>${e(r.reason||'Equipment inspection')}<small>${e(r.details||'No notes')}</small></td><td>${e(formatDate(r.started_at))}</td><td>${e(formatDate(r.completed_at))}</td><td>${status(r.status)}</td></tr>`).join('')):empty('No maintenance records','Start maintenance from an equipment detail screen.')}</section>`;
  }

  function reports() {
    const tx=model.transactions,completed=tx.filter(r=>r.status==='COMPLETED'),revenue=tx.filter(r=>['ACTIVE','COMPLETED'].includes(r.status)).reduce((s,r)=>s+Number(r.rental_fee||0),0),overdue=tx.filter(r=>r.status==='ACTIVE'&&r.due_at&&new Date(r.due_at.replace(' ','T')+'+08:00')<new Date()).length;
    const usage=new Map();for(const r of tx)usage.set(r.item_name,(usage.get(r.item_name)||0)+1);const popular=[...usage].sort((a,b)=>b[1]-a[1]).slice(0,5);
    return `${pageHeader('BUSINESS INSIGHTS','Reports','A practical overview of revenue, transactions, utilization, and risk.','<button class="primary" id="report-export">Export report</button>')}<div class="module-stats report-stats"><article><span>Recorded fees</span><strong>${money(revenue)}</strong></article><article><span>All transactions</span><strong>${tx.length}</strong></article><article><span>Completed</span><strong>${completed.length}</strong></article><article><span>Currently overdue</span><strong>${overdue}</strong></article></div><div class="report-grid"><section class="panel report-card"><h3>Most rented equipment</h3>${popular.length?popular.map(([name,count],index)=>`<div class="rank-row"><span>${index+1}</span><strong>${e(name)}</strong><em>${count} rental(s)</em></div>`).join(''):empty('No utilization data','Completed and active rentals will be ranked here.')}</section><section class="panel report-card"><h3>Operational summary</h3><dl class="report-list"><div><dt>Active customers</dt><dd>${model.customers.filter(c=>c.is_active!==false).length}</dd></div><div><dt>Equipment in maintenance</dt><dd>${model.maintenance.filter(r=>r.status==='IN_PROGRESS').length}</dd></div><div><dt>Active rates</dt><dd>${activeRates().length}</dd></div><div><dt>Registered terminals</dt><dd>${model.terminals.length}</dd></div></dl></section></div>`;
  }

  function settings(user,appearance) {
    const s=model.settings||{},owner=user.role==='OWNER';
    return `${pageHeader('WORKSPACE PREFERENCES','Settings','Manage appearance, business details, and staff access.')}<div class="settings-grid"><section class="panel settings-card">${appearance}</section><section class="panel settings-card"><span class="eyebrow">BUSINESS PROFILE</span><h3>Rental workspace</h3>${owner?`<form id="business-form" class="admin-form"><label>Business name<input name="businessName" value="${e(s.business_name||'Rent & Play')}" required/></label><label>Location<input name="location" value="${e(s.location||'Los Baños, Laguna')}" required/></label><div class="form-grid"><label>Currency<input name="currency" value="${e(s.currency||'PHP')}" maxlength="3" required/></label><label>Timezone<input name="timezone" value="${e(s.timezone||'Asia/Manila')}" required/></label></div><label>Late grace period (hours)<input name="defaultLateGraceHours" type="number" min="0" max="168" value="${e(s.default_late_grace_hours||0)}"/></label><p class="form-error"></p><button class="primary" type="submit">Save business settings</button></form>`:`<div class="settings-readonly"><strong>${e(s.business_name||'Rent & Play')}</strong><p>${e(s.location||'Los Baños, Laguna')}</p><small>Only owners can update business settings.</small></div>`}</section>${owner?users():''}</div>`;
  }

  function users() {
    return `<section class="panel settings-card settings-users"><div class="settings-title"><div><span class="eyebrow">TEAM ACCESS</span><h3>Users</h3></div><button class="secondary" id="user-add">Add user</button></div>${table(['USER','ROLE','LAST LOGIN','STATUS',''],model.users.map(u=>`<tr><td><strong>${e(u.full_name)}</strong><small>${e(u.email)}</small></td><td>${e(u.role)}</td><td>${e(formatDate(u.last_login_at))}</td><td>${status(u.is_active===false?'Inactive':'Active')}</td><td><button class="text-button" data-user-toggle="${e(u.id)}">${u.is_active===false?'Activate':'Deactivate'}</button></td></tr>`).join(''))}</section>`;
  }

  function userForm() {showModal('Add workspace user',`<form id="user-form" class="admin-form"><label>Full name<input name="fullName" required maxlength="150"/></label><label>Email<input name="email" type="email" required maxlength="191"/></label><label>Role<select name="role"><option>OPERATOR</option><option>OWNER</option></select></label><label>Temporary password<input name="password" type="password" minlength="12" required/><small>Minimum 12 characters. Ask the user to reset it after signing in.</small></label><p class="form-error"></p><div class="form-actions"><button type="button" class="secondary" data-close>Cancel</button><button class="primary" type="submit">Create user</button></div></form>`);modal.querySelector('[data-close]').onclick=()=>modal.close();modal.querySelector('form').onsubmit=async event=>{event.preventDefault();const form=event.currentTarget;try{await api('/users',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(form)))});await refresh();modal.close();toast('User created.');redraw();}catch(problem){form.querySelector('.form-error').textContent=problem.message;}};}

  function render(page,user,appearance) {if(!model)return `<section class="panel module-loading"><span class="session-spinner"></span><p>Loading ${e(page.toLowerCase())}…</p></section>`;if(page==='Customers')return customers();if(['Rentals','Returns','Transaction History'].includes(page))return transactions(page);if(page==='Rates & Fees')return rates();if(page==='Maintenance')return maintenance();if(page==='Reports')return reports();if(page==='Settings')return settings(user,appearance);return ''}

  function bind(page,user,rerender) {
    if(!['Customers','Rates & Fees','Rentals','Returns','Transaction History','Maintenance','Reports','Settings'].includes(page))return;
    redraw=rerender;
    if(!model){load().then(rerender).catch(problem=>toast(problem.message));return;}
    const searchBox=document.querySelector('#module-search');if(searchBox)searchBox.oninput=event=>{search=event.target.value;rerender();document.querySelector('#module-search')?.focus();};
    document.querySelector('#customer-add')?.addEventListener('click',()=>customerForm());document.querySelectorAll('[data-customer-edit]').forEach(button=>button.onclick=()=>customerForm(model.customers.find(c=>c.id===button.dataset.customerEdit)));
    document.querySelectorAll('[data-customer-action]').forEach(button=>button.onclick=async()=>{const c=model.customers.find(v=>v.id===button.dataset.customerAction);await api(`/customers/${c.id}`,{method:'PATCH',body:JSON.stringify({action:c.is_active===false?'restore':'archive'})});await refresh();toast(c.is_active===false?'Customer restored.':'Customer archived.');rerender();});
    document.querySelector('#rate-add')?.addEventListener('click',rateForm);
    document.querySelector('#business-form')?.addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget;try{await api('/settings',{method:'PATCH',body:JSON.stringify(Object.fromEntries(new FormData(form)))});await refresh();toast('Business settings saved.');rerender();}catch(problem){form.querySelector('.form-error').textContent=problem.message;}});
    document.querySelector('#user-add')?.addEventListener('click',userForm);document.querySelectorAll('[data-user-toggle]').forEach(button=>button.onclick=async()=>{const u=model.users.find(v=>v.id===button.dataset.userToggle);await api(`/users/${u.id}`,{method:'PATCH',body:JSON.stringify({role:u.role,isActive:u.is_active===false})});await refresh();toast('User access updated.');rerender();});
    document.querySelector('#report-export')?.addEventListener('click',()=>{const rows=[['Rental code','Equipment','Customer','Status','Rental fee','Deposit','Due','Returned'],...model.transactions.map(r=>[r.rental_code,r.item_name,r.customer_name,r.status,r.rental_fee,r.deposit_amount,r.due_at,r.confirmed_return_at])],cell=value=>{const text=String(value??''),safe=/^[=+@\-\t\r]/.test(text)?"'"+text:text;return '"'+safe.replaceAll('"','""')+'"';};const csv='\uFEFF'+rows.map(row=>row.map(cell).join(',')).join('\r\n'),url=URL.createObjectURL(new Blob([csv],{type:'text/csv'})),a=document.createElement('a');a.href=url;a.download='rent-and-play-report.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Report exported.');});
  }
  return {load,refresh,render,bind};
}
