services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: rent_and_play
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - rent_play_pgdata:/var/lib/postgresql/data

volumes:
  rent_play_pgdata:
